#!/usr/bin/env bash
# Assembles the static site (docs + playground) into a deployable directory.
#
#   web/build.sh [outdir]     # default outdir: _site
#
# Requires Go. The result is genuinely self-contained — no CDN, no web fonts,
# no third-party request of any kind. Serve it with any static file server,
# e.g. `python -m http.server -d _site`.
#
# Where the site lives, and where its "view this file on GitHub" links point.
# These are the only two places to change after a rename or a transfer; they
# are substituted into the HTML (canonical, og:url, og:image) and into site.js.
# Override from the environment to build a copy for somewhere else.
SITE_URL="${SITE_URL:-https://castux.github.io/thunky}"
REPO_URL="${REPO_URL:-https://github.com/Castux/thunky}"
REPO_BRANCH="${REPO_BRANCH:-master}"

set -euo pipefail
cd "$(dirname "$0")/.."

out="${1:-_site}"
rm -rf "$out"
mkdir -p "$out/docs" "$out/examples" "$out/vendor"

# The site is Thunky-branded; the wasm binary keeps the module name.

# The wasm build of the compiler+runtime, and the Go-version-matched JS shim.
GOOS=js GOARCH=wasm go build -trimpath -ldflags="-s -w" -o "$out/thunky.wasm" .
goroot="$(go env GOROOT)"
if [ -f "$goroot/lib/wasm/wasm_exec.js" ]; then
    cp "$goroot/lib/wasm/wasm_exec.js" "$out/"
else
    cp "$goroot/misc/wasm/wasm_exec.js" "$out/"   # Go < 1.24 layout
fi

# Static assets. logo.svg lives at the repository root rather than in web/ so
# that the same relative path works from README.md on GitHub and from the
# rendered README at the root of this site; it is both the favicon and the mark
# at the top of the overview page. The raster icons and the link-preview image
# are generated by etc/make-images.py and committed.
cp web/style.css web/thunky-mode.js web/runner.js web/worker.js \
   web/favicon.ico web/apple-touch-icon.png web/og-image.png \
   logo.svg "$out/"
cp web/vendor/codemirror.min.js web/vendor/codemirror.min.css \
   web/vendor/marked.min.js "$out/vendor/"

# The files carrying a URL get it substituted on the way in.
subst() {
    sed -e "s|__SITE_URL__|$SITE_URL|g" \
        -e "s|__REPO_URL__|$REPO_URL|g" \
        -e "s|__REPO_BRANCH__|$REPO_BRANCH|g" "$1" > "$out/$(basename "$1")"
}
for f in web/index.html web/playground.html web/404.html web/robots.txt \
         web/site.js web/playground.js; do
    subst "$f"
done

# A sitemap, because the sidebar that links every page is built by JavaScript
# and a crawler will not see it. The page ids come from the PAGES table in
# site.js so the two cannot drift.
{
    echo "$SITE_URL/"
    echo "$SITE_URL/playground.html"
    sed -n 's/^ *{ id: "\([a-z0-9]*\)".*/\1/p' web/site.js |
        grep -v '^home$' |
        sed "s|^|$SITE_URL/index.html?page=|"
} > "$out/sitemap.txt"

# The markdown the site renders, and the example programs the playground loads.
# docs/implementation/ is intentionally excluded — see the note in web/site.js.
mkdir -p "$out/docs/tutorial"
cp README.md LICENSE.md "$out/"
cp docs/*.md "$out/docs/"
cp docs/tutorial/*.md "$out/docs/tutorial/"
cp examples/*.þ "$out/examples/"

# The exercise sets, their data files, and the helper module a few of them
# import. The playground fetches modules and hands them to the runtime, since
# the browser has no filesystem to resolve `import euler` against.
mkdir -p "$out/examples/euler/data" "$out/examples/rosetta"
cp examples/euler/*.þ examples/euler/*.th "$out/examples/euler/"
cp examples/euler/data/*.txt "$out/examples/euler/data/"
cp examples/rosetta/*.þ "$out/examples/rosetta/"

echo "site assembled in $out/"
